'use client';
import {useEffect,useState} from 'react';
import {Users,Check,CalendarDays,ArrowRight,Play,Plus,RefreshCw} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {demoAccount,demoRequest} from '@/lib/demo-api';
import {topicCatalog} from '@/lib/topic-catalog';

async function request(data?:unknown){if(demoAccount())return demoRequest('action=teacher-summary',data);const r=await fetch('/api/app'+(data?'':'?action=teacher-summary'),data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:undefined);const d:any=await r.json();if(!r.ok)throw new Error(d.error||'불러오지 못했어요.');return d}
export default function TeacherDashboard({groupId,catalogOnly=false,onGroup,onChoose,onCreate,onVideo}:{groupId?:string;catalogOnly?:boolean;onGroup:(id:string)=>void;onChoose:(id:string,catalogId:string)=>void;onCreate:()=>void;onVideo:()=>void}){
 const [groups,setGroups]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[pending,setPending]=useState(''),[selected,setSelected]=useState<Record<string,string>>({}),[target,setTarget]=useState('');
 async function refresh(){const d=await request();setGroups(d.groups);setTarget(v=>v||d.groups[0]?.id||'')}
 useEffect(()=>{refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const visible=groupId?groups.filter(g=>g.id===groupId):groups;
 const current=(g:any)=>g.topics.find((t:any)=>t.id===selected[g.id])||g.topics[0];
 const total=visible.reduce((n,g)=>n+g.studentCount,0),active=visible.reduce((n,g)=>n+(current(g)?.active||0),0),complete=visible.reduce((n,g)=>n+(current(g)?.complete||0),0);
 async function assign(g:any,t:any){setPending(t.id);setError('');try{await request({action:'allocate',groupId:g.id,topicId:t.id});await refresh()}catch(e:any){setError(e.message)}finally{setPending('')}}
 if(loading)return <p className="card" role="status">수업 현황을 불러오고 있어요…</p>;
 return <div className="teacher-dashboard">
 <div className="section-head"><div><p className="eyebrow">선생님</p><h1>{catalogOnly?'토론 주제':groupId?visible[0]?.name||'그룹 현황':'수업 현황'}</h1></div><div className="row"><button className="outline" aria-label="수업 현황 새로고침" onClick={()=>refresh().catch(e=>setError(e.message))}><RefreshCw size={16}/>새로고침</button><button className="primary" onClick={onCreate}><Plus size={17}/>그룹 만들기</button></div></div>
 {error&&<p className="error" role="alert">{error}</p>}
 {!catalogOnly&&<><div className="teacher-stats"><section className="card"><Users size={21}/><p>그룹 학생</p><strong>{total}<small>명</small></strong></section><section className="card"><CalendarDays size={21}/><p>참여율</p><strong>{total?Math.round(active/total*100):0}<small>%</small></strong><span>{active} / {total}명 참여</span></section><section className="card"><Check size={21}/><p>준비 완료</p><strong>{complete}<small>명</small></strong><span>{total-complete}명 준비 전·진행 중</span></section></div><p className="tiny">각 그룹에서 선택한 회차 기준 · 참여는 대화 전송 또는 생각 기록을 남긴 학생 수예요. 여러 그룹에 속한 학생은 그룹별로 집계돼요.</p>
 <div className="teacher-groups">{visible.map(g=>{const t=current(g);return <section className="card" key={g.id}><div className="section-head"><div><button className="group-heading" onClick={()=>onGroup(g.id)}>{g.name}<ArrowRight size={17}/></button><p className="muted">학생 {g.studentCount}명 · 참여 코드 <b>{g.code}</b></p></div><button className="outline" onClick={()=>onChoose(g.id,topicCatalog[0].id)}>주제 고르기</button></div>
 {t?<><label className="form-field lesson-select">토론 회차<select value={t.id} onChange={e=>setSelected(s=>({...s,[g.id]:e.target.value}))}>{g.topics.map((x:any,i:number)=><option key={x.id} value={x.id}>{g.topics.length-i}회차 · {x.title}</option>)}</select></label><div className="lesson-meta"><span>{new Date(t.due).toLocaleString('ko-KR',{dateStyle:'medium',timeStyle:'short'})}</span><span>{t.active}/{g.studentCount}명 참여 · {t.complete}명 준비 완료</span></div><Progress className="pet-progress" value={g.studentCount?t.active/g.studentCount*100:0} aria-label={g.name+' 참여율'}/>
 <div className="allocation-box"><div className="section-head"><h2>토론자 배정</h2><button className="primary" disabled={!!pending||t.complete<2} onClick={()=>assign(g,t)}>{pending===t.id?'배정 중…':t.allocation?'다시 배정':'AI 토론자 배정'}</button></div><p className="muted">준비 완료: {t.complete}명</p><p className="tiny">이전 참여가 적은 학생부터 최대 6명을 고르고, AI가 준비 내용을 보고 찬반을 최대 3:3으로 배정해요. 나머지는 배심원이에요.</p>
 {t.allocation?<><p className="allocation-time">배정 결과 · {new Date(t.allocation.created).toLocaleString('ko-KR')}</p><div className="teams">{[['pro','찬성측'],['con','반대측'],['jury','배심원']].map(([role,label])=><section key={role}><h3>{label}</h3>{t.allocation.assignments.filter((a:any)=>a.role===role).map((a:any)=><span className="pill" key={a.id}>{a.nickname}</span>)}{!t.allocation.assignments.some((a:any)=>a.role===role)&&<p className="muted">없음</p>}</section>)}</div></>:<p className="assignment-empty">{t.complete<2?'준비를 마친 학생이 2명 이상이면 배정할 수 있어요.':'배정 버튼을 누르면 찬성측·반대측·배심원 명단이 여기에 표시돼요.'}</p>}</div>
 {groupId&&<div className="roster"><h2>학생별 준비 현황</h2>{t.students.map((s:any)=><div key={s.id}><span>{s.nickname}</span><span className="pill">{s.complete?'준비 완료':s.active?'준비 중':'아직 참여 전'}</span></div>)}{!t.students.length&&<p className="muted">아직 참여한 학생이 없어요.</p>}</div>}</>:<div className="assignment-empty"><p>아직 등록한 토론이 없어요.</p><button className="text-button" onClick={()=>onChoose(g.id,topicCatalog[0].id)}>첫 주제 고르기 <ArrowRight size={17}/></button></div>}</section>})}</div>
 {!visible.length&&<section className="card empty"><Users size={35}/><h2>첫 그룹을 만들어 보세요</h2><p>학생이 코드로 참여하면 수업 현황을 확인할 수 있어요.</p><button className="primary" onClick={onCreate}>그룹 만들기</button></section>}</>}
 {!groupId&&<section className="catalog-section"><div className="section-head"><h2>토론 주제 목록</h2><span className="pill">{topicCatalog.length}개 주제</span></div><div className="catalog-grid">{topicCatalog.map(item=><article className="card catalog-card" key={item.id}><button className="catalog-video" onClick={onVideo} aria-label={item.videoTitle+' 미리보기'}><img src="/assets/history.png" alt="조선 역사 영상"/><span className="play-circle"><Play size={23}/></span></button><span className="pill">역사</span><h3>{item.title}</h3><p className="muted">{item.videoTitle}</p><label className="form-field">수업 그룹<select value={target} onChange={e=>setTarget(e.target.value)} disabled={!groups.length}><option value="">그룹 선택</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><button className="primary full" disabled={!target} onClick={()=>onChoose(target,item.id)}>이 주제로 수업하기</button>{!groups.length&&<button className="text-button" onClick={onCreate}>먼저 그룹 만들기</button>}</article>)}</div></section>}
 </div>
}
