import {topicCatalog,lessonForTitle} from './topic-catalog';
const DATA='ssinggeut-demo-v1', ACCOUNT='ssinggeut-demo-account', SCENARIO='ssinggeut-presentation';
export const demoAccounts=[{id:'선생님',nickname:'체험 선생님',role:'teacher'},...Array.from({length:6},(_,i)=>({id:`학생0${i+1}`,nickname:`학생 ${i+1}`,role:'student'}))];
export function demoAccount(){return typeof window==='undefined'?null:sessionStorage.getItem(ACCOUNT)}
type DemoUser={id:string;loginId?:string;nickname:string;role:string};
const normalized=(value:string)=>value.trim().normalize('NFC');
const loginKey=(value:string)=>normalized(value).toLowerCase();
export function getDemoAccounts():DemoUser[]{if(typeof window==='undefined')return demoAccounts;const d=load();return isPresenting()?d.accounts:[...demoAccounts,...(d.accounts||[])]}
export function loginDemo(value:string){const user=getDemoAccounts().find(a=>loginKey(a.loginId||a.id)===loginKey(value));if(!user)throw new Error('아직 없는 아이디예요. 새 체험 계정 만들기에서 가입해 주세요.');sessionStorage.setItem(ACCOUNT,user.id);window.location.reload()}
export function registerDemo(value:string,nickname:string,role:'student'|'teacher'='student'){if(role!=='student'&&role!=='teacher')throw new Error('가입 유형을 선택해 주세요.');const loginId=normalized(value),name=normalized(nickname);if(!/^[\p{L}\p{N}_.-]{1,30}$/u.test(loginId))throw new Error('아이디는 1~30자의 한글·영문·숫자·밑줄·점·하이픈으로 입력해 주세요.');if(!name||name.length>20)throw new Error('닉네임은 1~20자로 입력해 주세요.');if(getDemoAccounts().some(a=>loginKey(a.loginId||a.id)===loginKey(loginId)))throw new Error('이미 사용 중인 아이디예요. 로그인하거나 다른 아이디를 정해 주세요.');const d=load(),user={id:crypto.randomUUID(),loginId,nickname:name,role};d.accounts=[...(d.accounts||[]),user];persist(d);sessionStorage.setItem(ACCOUNT,user.id);window.location.reload()}
export function exitDemo(){if(isPresenting()){endPresentation();return;}sessionStorage.removeItem(ACCOUNT);window.location.reload()}
const stamp=()=>new Date().toISOString();
function load(){const scene=sessionStorage.getItem(SCENARIO);if(scene)return JSON.parse(scene).data;const saved=localStorage.getItem(DATA);if(saved){const d=JSON.parse(saved);if(!d.membershipVersion){d.membershipVersion=2;persist(d)}return d;}const c=topicCatalog[0];return {membershipVersion:2,groups:[{id:'demo-group',owner:'선생님',name:'체험 토론반',code:'DEMO0001',created:stamp()}],topics:[{id:'demo-topic',group_id:'demo-group',title:c.title,context:c.context,due:new Date(Date.now()+7*86400000).toISOString(),created:stamp()}],members:[{group_id:'demo-group',user_id:'선생님'}],sessions:[],messages:[],allocations:[],attendance:[]}}
function persist(d:any){try{const scene=sessionStorage.getItem(SCENARIO);if(scene){const state=JSON.parse(scene);state.data=d;sessionStorage.setItem(SCENARIO,JSON.stringify(state))}else localStorage.setItem(DATA,JSON.stringify(d))}catch{throw new Error('브라우저 저장 공간이 부족해 체험 기록을 저장하지 못했어요.')}}
async function bridge(body:any){const r=await fetch('/api/app',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'씽씽에 연결하지 못했어요.');return d}
export async function demoRequest(query='',body?:any){
 const accounts=getDemoAccounts(),uid=demoAccount(),user=accounts.find(a=>a.id===uid);if(!user)throw new Error('체험 계정을 선택해 주세요.');
 const d=load(),p=new URLSearchParams(query),action=body?.action||p.get('action');
 const owner=(gid:string)=>{const g=d.groups.find((g:any)=>g.id===gid&&g.owner===uid);if(!g)throw new Error('그룹 선생님만 할 수 있어요.');return g};
 const member=(gid:string)=>{if(!d.members.some((m:any)=>m.group_id===gid&&m.user_id===uid))throw new Error('이 그룹에 참여해 주세요.')};
 const session=(id:string)=>{const s=d.sessions.find((s:any)=>s.id===id&&s.owner===uid);if(!s)throw new Error('내 기록만 열 수 있어요.');return s};
 const roster=(gid:string)=>accounts.filter(a=>a.role==='student'&&d.members.some((m:any)=>m.group_id===gid&&m.user_id===a.id));
 const latest=(tid:string,id:string)=>d.sessions.filter((s:any)=>s.topic_id===tid&&s.owner===id).sort((a:any,b:any)=>b.updated.localeCompare(a.updated))[0];
 const allocation=(gid:string,tid?:string)=>{const a=d.allocations.filter((a:any)=>a.group_id===gid&&(!tid||a.topic_id===tid)).at(-1);return a&&a.assignments.length===roster(gid).length&&a.assignments.every((x:any)=>roster(gid).some(r=>r.id===x.id))?a:null};
 const lesson=(g:any,t:any)=>{const students=roster(g.id).map(r=>{const s=latest(t.id,r.id);return {id:r.id,nickname:r.nickname,active:!!s&&(!!(s.question||s.opinion||s.evidence)||d.messages.some((m:any)=>m.session_id===s.id)),complete:!!s?.complete,stance:s?.stance||'undecided',updated:s?.updated||null}});return {...t,students,active:students.filter(s=>s.active).length,complete:students.filter(s=>s.complete).length,pro:students.filter(s=>s.complete&&s.stance==='pro').length,con:students.filter(s=>s.complete&&s.stance==='con').length,allocation:allocation(g.id,t.id)}};
 const touch=()=>{const day=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'});if(!d.attendance.some((a:any)=>a.user_id===uid&&a.day===day))d.attendance.push({user_id:uid,day})};
 if(!body){
 if(action==='teacher-summary'){if(user.role!=='teacher')throw new Error('선생님 화면이에요.');return {groups:d.groups.filter((g:any)=>g.owner===uid).map((g:any)=>({...g,studentCount:roster(g.id).length,topics:d.topics.filter((t:any)=>t.group_id===g.id).slice().reverse().map((t:any)=>lesson(g,t))}))}}
 if(action==='session'){const s=session(p.get('id')||'');return {session:s,messages:d.messages.filter((m:any)=>m.session_id===s.id)}}
 if(action==='group'){const gid=p.get('id')||'';member(gid);const g=d.groups.find((g:any)=>g.id===gid),ts=d.topics.filter((t:any)=>t.group_id===gid).slice().reverse(),a=allocation(gid);return {group:g,topics:ts,roster:g.owner===uid?roster(gid):[],progress:[],allocation:a?{...a,assignments:JSON.stringify(a.assignments)}:null}}
 return {signedIn:true,conversationCount:d.messages.filter((m:any)=>m.role==='user'&&d.sessions.some((s:any)=>s.id===m.session_id&&s.owner===uid)).length,demo:true,presenting:isPresenting(),admin:false,profile:{...user},groups:d.groups.filter((g:any)=>d.members.some((m:any)=>m.group_id===g.id&&m.user_id===uid)),sessions:d.sessions.filter((s:any)=>s.owner===uid).slice().reverse(),attendance:d.attendance.filter((a:any)=>a.user_id===uid)};
 }
 let result:any={ok:true};
 if(action==='session-create'){const t=d.topics.find((t:any)=>t.id===body.topicId);if(!t)throw new Error('배정된 주제를 선택해 주세요.');member(t.group_id);const id=crypto.randomUUID();d.sessions.push({id,owner:uid,topic_id:t.id,title:t.title,question:'',opinion:'',evidence:'',next_question:'',stance:'undecided',complete:0,created:stamp(),updated:stamp()});result={id}}
 else if(action==='save'){const s=session(body.sessionId);member(d.topics.find((t:any)=>t.id===s.topic_id)?.group_id);if(body.complete&&(!s.question||!s.opinion||!s.evidence))throw new Error('대화에서 질문, 내 생각, 직접 확인한 근거를 남겨 주세요.');Object.assign(s,{complete:body.complete?1:0,updated:stamp()});touch()}
 else if(action==='chat'){const s=session(body.sessionId);member(d.topics.find((t:any)=>t.id===s.topic_id)?.group_id);const {answer,notes}=await bridge({action:'demo-chat',catalogId:lessonForTitle(s.title).id,message:body.message,notes:{question:s.question,opinion:s.opinion,evidence:s.evidence,next_question:s.next_question},history:d.messages.filter((m:any)=>m.session_id===s.id).slice(-12).map((m:any)=>({role:m.role,content:m.content}))});d.messages.push({id:crypto.randomUUID(),session_id:s.id,role:'user',content:body.message,created:stamp()},{id:crypto.randomUUID(),session_id:s.id,role:'assistant',content:answer,created:stamp()});Object.assign(s,notes,{complete:0,updated:stamp()});touch();result={answer,notes}}
 else if(action==='group-leave'){member(body.groupId);if(d.groups.find((g:any)=>g.id===body.groupId)?.owner===uid)throw new Error('그룹을 만든 선생님은 나갈 수 없어요.');d.members=d.members.filter((m:any)=>!(m.group_id===body.groupId&&m.user_id===uid));}
 else if(action==='group-create'){if(user.role!=='teacher')throw new Error('선생님만 그룹을 만들 수 있어요.');const id=crypto.randomUUID();d.groups.push({id,owner:uid,name:body.name,code:crypto.randomUUID().slice(0,8).toUpperCase(),created:stamp()});d.members.push({group_id:id,user_id:uid});result={id}}
 else if(action==='group-join'){const g=d.groups.find((g:any)=>g.code===body.code.trim().toUpperCase());if(!g)throw new Error('코드를 확인해 주세요.');if(!d.members.some((m:any)=>m.group_id===g.id&&m.user_id===uid))d.members.push({group_id:g.id,user_id:uid});result={id:g.id}}
 else if(action==='topic-create'){owner(body.groupId);const c=topicCatalog.find(t=>t.id===body.catalogId);if(!c||!Number.isFinite(Date.parse(body.due))||Date.parse(body.due)<=Date.now())throw new Error('주제와 앞으로의 날짜를 선택해 주세요.');const id=crypto.randomUUID();d.topics.push({id,group_id:body.groupId,title:c.title,context:c.context,due:body.due,created:stamp()});result={id}}
 else if(action==='allocate'){const g=owner(body.groupId);if(!d.topics.some((t:any)=>t.id===body.topicId&&t.group_id===g.id))throw new Error('그룹의 주제를 선택해 주세요.');const rs=roster(g.id),counts:Record<string,number>={};d.allocations.filter((a:any)=>a.group_id===g.id).forEach((a:any)=>a.assignments.forEach((r:any)=>{if(r.role!=='jury')counts[r.id]=(counts[r.id]||0)+1}));const requiredId=isPresenting()?d.requiredDebaterId:undefined;const candidates=rs.filter(r=>latest(body.topicId,r.id)?.complete||r.id===requiredId).map(r=>{const s=latest(body.topicId,r.id);return {id:r.id,question:s?.question||'',opinion:s?.opinion||'',evidence:s?.evidence||''}});if(candidates.length<2)throw new Error('준비를 마친 학생이 2명 이상 필요해요.');const response=await bridge({action:'demo-allocate',catalogId:lessonForTitle(d.topics.find((t:any)=>t.id===body.topicId)?.title).id,candidates,counts,requiredId});const assignments=rs.map(r=>({id:r.id,nickname:r.nickname,role:response.assignments.find((a:any)=>a.id===r.id)?.role||'jury'}));d.allocations.push({id:crypto.randomUUID(),group_id:g.id,topic_id:body.topicId,assignments,created:stamp()});result={assignments}}
 else throw new Error('이 기능은 실제 계정에서 이용해 주세요.');
 persist(d);return result;
}

export function isPresenting(){return typeof window!=='undefined'&&!!sessionStorage.getItem(SCENARIO)}
export function endPresentation(){const scene=sessionStorage.getItem(SCENARIO);if(!scene)return;const previous=JSON.parse(scene).previous;sessionStorage.removeItem(SCENARIO);if(previous)sessionStorage.setItem(ACCOUNT,previous);else sessionStorage.removeItem(ACCOUNT);window.location.reload()}
export function startPresentation(group?:any,topic?:any){
 if(isPresenting())return;
 const c=lessonForTitle(topic?.title),time=stamp(),gid='presentation-group',tid='presentation-topic';
 const names=['김일번','김이번','김삼번','김사번','김오번','김육번','김칠번','김팔번','김구번'];
 const accounts=[{id:'presentation-teacher',loginId:'시연 선생님',nickname:'시연 선생님',role:'teacher'},...names.map((nickname,i)=>({id:'presentation-student-'+i,loginId:'시연 학생 '+(i+1),nickname,role:'student'})),{id:'presentation-minah',loginId:'안민아',nickname:'안민아',role:'student'}];
 const questions=c.id==='joseon-princes'?['왕자의 난은 결과만 보고 판단해도 될까?','이방석이 세자로 정해진 이유는 무엇일까?','군사를 통제하는 방식이 왜 갈등이 되었을까?','정도전은 건국 뒤 어떤 역할을 했을까?','함께 건국에 참여한 사람들은 왜 갈라졌을까?','기록을 남긴 사람의 입장도 확인해야 할까?','이방원은 건국 과정에서 무엇을 했을까?','사건이 일어난 순서를 정리하면 이해가 쉬워질까?','이방원이 문과에 합격한 사실은 어떤 의미일까?']:['판단하기 전에 어떤 사실을 확인해야 할까?','선택의 이유와 결과를 따로 보면 어떨까?','다른 입장에서는 무엇을 중요하게 볼까?','이 상황에 다른 선택지는 없었을까?','모두에게 같은 기준을 적용할 수 있을까?','어떤 자료가 내 생각을 바꿀 수 있을까?','아직 알려지지 않은 부분은 무엇일까?','주장과 사실은 어떻게 구분할까?','이 결정의 영향을 받는 사람은 누구일까?'];
 const opinions=['결과만으로 판단하기는 어렵다고 생각해.','선택의 이유도 함께 살펴야 한다고 생각해.','사람마다 중요하게 생각하는 기준이 다른 것 같아.','다른 방법이 있었는지 비교하고 싶어.','같은 기준이 언제나 공정한지는 더 생각해 봐야겠어.','주장을 뒷받침할 근거가 충분한지 살펴보고 싶어.','아직 판단을 내리기 어려워.','사실과 내 해석을 나눠 보고 싶어.','결정에 참여하지 못한 사람도 살펴보고 싶어.'];
 const facts=['1398년에 정도전과 이방석이 죽임을 당했다.','이성계는 1392년에 이방석을 세자로 정했다.','정도전은 왕자들의 군사에 대한 통제를 강화하려 했다.','정도전은 조선 건국에 참여하고 새 나라의 제도를 마련했다.','이방원과 정도전 모두 조선 건국에 참여했다.','태조실록에는 이방원이 정도전의 목을 베게 했다고 기록되어 있다.'];
 const sessions=names.map((name,i)=>({id:'presentation-session-'+i,owner:accounts[i+1].id,topic_id:tid,title:c.title,question:questions[i],opinion:opinions[i],evidence:i<6?'[시연 예시] '+(c.id==='joseon-princes'?'제공 영상에서 확인한 내용: '+facts[i]:c.context.split('영상 내용: ')[1]?.split(' 영상에')[0]||c.context):'',next_question:i<6?'내 생각과 다른 설명을 뒷받침하는 자료도 있을까?':'',stance:'undecided',complete:i<6?1:0,created:time,updated:new Date(Date.now()-i*60000).toISOString()}));
 const messages=sessions.flatMap((r,i)=>[{id:r.id+'-1',session_id:r.id,role:'user',content:r.question,created:time},{id:r.id+'-2',session_id:r.id,role:'assistant',content:c.id==='joseon-princes'?['판단의 기준으로 어떤 점을 먼저 살펴보고 싶어?','세자 책봉 장면에서 무엇을 더 확인하고 싶어?','누가 어떤 군사를 통제했는지 자료에서 찾아볼까?','영상에 나온 역할 중 더 알아보고 싶은 것은 뭐야?','두 사람이 어떤 점에서 다른 생각을 했는지 확인하려면 무엇이 필요할까?','기록의 작성 시기를 어디에서 확인할 수 있을까?','영상에서 기억나는 건국 장면을 하나 골라볼까?','먼저 어떤 사건부터 순서대로 놓아볼까?','문과가 무엇인지 설명하는 자료부터 찾아볼까?'][i]:'영상에서 그 질문이 떠오른 장면은 어디였어?',created:time},{id:r.id+'-3',session_id:r.id,role:'user',content:r.opinion+(r.evidence?' '+r.evidence:''),created:time},{id:r.id+'-4',session_id:r.id,role:'assistant',content:'그 생각을 확인하려면 어떤 자료를 더 찾아보고 싶어?',created:time}]);
 const data={membershipVersion:2,requiredDebaterId:'presentation-minah',accounts,groups:[{id:gid,owner:accounts[0].id,name:group?.name||'우리 그룹',code:group?.code||'SHOW0009',created:time}],topics:[{id:tid,group_id:gid,title:c.title,context:c.context,due:topic?.due||new Date(Date.now()+7*86400000).toISOString(),created:time}],members:accounts.map(a=>({group_id:gid,user_id:a.id})),sessions,messages,allocations:[],attendance:accounts.slice(1,10).map(a=>({user_id:a.id,day:time.slice(0,10)}))};
 sessionStorage.setItem(SCENARIO,JSON.stringify({previous:demoAccount(),data}));sessionStorage.setItem(ACCOUNT,accounts[0].id);window.location.reload();
}
