import {topicCatalog,lessonForTitle} from '@/lib/topic-catalog';
import {auth,profile,one,all,write,db,now,day,id,str,member,owner,ownSession,ai,coach,assignDebate,topicContext,Problem} from '@/lib/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
export const dynamic='force-dynamic';
const json=(d:any,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'no-store'}});
const fail=(e:unknown)=>{if(e instanceof Problem)return json({error:e.message},e.status);console.error('app failure',e instanceof Error?e.message:'unknown');return json({error:'연결에 문제가 생겼어. 입력한 내용을 지우지 말고 다시 시도해 줘.'},503)};
const validRoster=(assignments:any[],roster:any[])=>assignments.length===roster.length&&assignments.every(a=>roster.some(r=>r.id===a.id));
export async function GET(req:Request){try{
 if(!await getChatGPTUser())return json({signedIn:false});const u=await auth();const url=new URL(req.url);const action=url.searchParams.get('action');
 if(action==='teacher-summary'){
 const p=await profile(u);if(p.role!=='teacher'&&!u.admin)throw new Problem(403,'선생님만 볼 수 있어요.');
 const gs=await all('SELECT * FROM groups WHERE owner=? ORDER BY created DESC',u.userId);
 const result=[];
 for(const g of gs){
 const roster=await all('SELECT p.id,p.nickname FROM profiles p JOIN members m ON m.user_id=p.id WHERE m.group_id=? AND p.id<>? ORDER BY p.nickname',g.id,u.userId);
 const ts=await all('SELECT id,title,due,created FROM topics WHERE group_id=? ORDER BY created DESC',g.id);
 const lessons=[];
 for(const t of ts){
 const progress=await all(`SELECT s.owner,s.complete,s.stance,s.updated,CASE WHEN s.question<>'' OR s.opinion<>'' OR s.evidence<>'' OR EXISTS(SELECT 1 FROM messages msg WHERE msg.session_id=s.id) THEN 1 ELSE 0 END active FROM sessions s WHERE s.topic_id=? ORDER BY s.updated DESC,s.id DESC`,t.id);
 const latest=new Map();for(const row of progress)if(!latest.has(row.owner))latest.set(row.owner,row);
 const students=roster.map(r=>{const a=latest.get(r.id);return {...r,active:!!a?.active,complete:!!a?.complete,stance:a?.stance||'undecided',updated:a?.updated||null}});
 const allocation=await one('SELECT id,assignments,created FROM allocations WHERE group_id=? AND topic_id=? ORDER BY created DESC,id DESC LIMIT 1',g.id,t.id);
 lessons.push({...t,students,active:students.filter(r=>r.active).length,complete:students.filter(r=>r.complete).length,pro:students.filter(r=>r.complete&&r.stance==='pro').length,con:students.filter(r=>r.complete&&r.stance==='con').length,allocation:allocation&&validRoster(JSON.parse(allocation.assignments),roster)?{...allocation,assignments:JSON.parse(allocation.assignments)}:null});
 }
 result.push({...g,studentCount:roster.length,topics:lessons});
 }
 return json({groups:result});
 }
 if(action==='session'){const s=await ownSession(str(url.searchParams.get('id'),100,1),u.userId);return json({session:s,messages:await all('SELECT id,role,content,created FROM messages WHERE session_id=? ORDER BY created,id',s.id)})}
 if(action==='group'){const g=await member(str(url.searchParams.get('id'),100,1),u.userId);const ts=await all('SELECT * FROM topics WHERE group_id=? ORDER BY created DESC',g.id);const roster=g.owner===u.userId?await all('SELECT p.id,p.nickname FROM profiles p JOIN members m ON m.user_id=p.id WHERE m.group_id=? AND p.id<>?',g.id,g.owner):[];const progress=g.owner===u.userId&&ts.length?await all('SELECT owner,MAX(complete) complete FROM sessions WHERE topic_id=? GROUP BY owner',ts[0].id):[];const allocation=await one('SELECT * FROM allocations WHERE group_id=? ORDER BY created DESC LIMIT 1',g.id);const members=await all('SELECT user_id id FROM members WHERE group_id=? AND user_id<>?',g.id,g.owner);return json({group:g,topics:ts,roster,progress,allocation:allocation&&validRoster(JSON.parse(allocation.assignments),members)?allocation:null})}
 if(action==='requests'){if(!u.admin)throw new Problem(403,'관리자만 확인할 수 있어.');return json({requests:await all('SELECT r.*,p.nickname FROM teacher_requests r JOIN profiles p ON p.id=r.user_id ORDER BY r.created DESC')})}
 const p=await one('SELECT * FROM profiles WHERE id=?',u.userId);if(!p)return json({signedIn:true,admin:u.admin,profile:null});
 return json({signedIn:true,admin:u.admin,profile:p,request:await one('SELECT status,institution FROM teacher_requests WHERE user_id=?',u.userId),groups:await all('SELECT g.* FROM groups g JOIN members m ON m.group_id=g.id WHERE m.user_id=? ORDER BY g.created DESC',u.userId),sessions:await all('SELECT * FROM sessions WHERE owner=? ORDER BY updated DESC LIMIT 100',u.userId),attendance:await all('SELECT day FROM attendance WHERE user_id=? ORDER BY day DESC LIMIT 90',u.userId)})
 }catch(e){return fail(e)}}
export async function POST(req:Request){try{
 const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new Problem(403,'페이지를 새로 열고 다시 시도해 줘.');if(!req.headers.get('content-type')?.includes('application/json'))throw new Problem(415,'올바른 요청이 아니야.');
 const u=await auth();const raw=await req.text();if(raw.length>22000)throw new Problem(413,'내용을 조금 나누어 보내 줘.');let b:any;try{b=JSON.parse(raw)}catch{throw new Problem(400,'입력을 확인해 줘.')}const action=b.action;
 if(action==='signup'){const nickname=str(b.nickname,20,1);await write('INSERT INTO profiles(id,nickname,role,created) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET nickname=excluded.nickname',u.userId,nickname,'student',now());return json({ok:true})}
 if(action==='demo-chat'||action==='demo-allocate'){
 const selected=topicCatalog.find(t=>t.id===b.catalogId);if(!selected)throw new Problem(400,'주제를 다시 선택해 주세요.');
 if(!u.admin)throw new Problem(403,'실제 계정으로 로그인한 사이트 소유자만 체험 AI를 사용할 수 있어요.');
 if(action==='demo-chat'){
 const message=str(b.message,2500,1);const history=Array.isArray(b.history)?b.history.slice(-12).map((m:any)=>({role:m.role==='assistant'?'assistant':'user',content:str(m.content,2500)})):[];
 const previous:any={};for(const k of ['question','opinion','evidence','next_question'])previous[k]=str(b.notes?.[k]||'',1500);
 return json(await coach(u,[...history,{role:'user',content:message}],selected.title+'\n'+selected.context+(selected.id==='joseon-princes'?'\n'+topicContext:''),previous));
 }
 if(!Array.isArray(b.candidates)||b.candidates.length>60)throw new Problem(400,'배정할 학생을 확인해 주세요.');
 const candidates=b.candidates.map((c:any)=>({id:str(c.id,100,1),question:str(c.question,1500),opinion:str(c.opinion,1500),evidence:str(c.evidence,1500)}));
 if(new Set(candidates.map((c:any)=>c.id)).size!==candidates.length)throw new Problem(400,'학생이 중복되었어요.');
 const counts:Record<string,number>={};for(const c of candidates)counts[c.id]=Math.max(0,Math.min(10000,Number(b.counts?.[c.id])||0));
 return json({assignments:await assignDebate(u,selected.title,candidates,counts)});
 }
 const p=await profile(u);
 if(action==='teacher-request'){await write("INSERT INTO teacher_requests(user_id,name,institution,evidence,status,created) VALUES(?,?,?,?,'pending',?) ON CONFLICT(user_id) DO UPDATE SET name=excluded.name,institution=excluded.institution,evidence=excluded.evidence,status='pending',created=excluded.created",u.userId,str(b.name,80,1),str(b.institution,160,1),str(b.evidence,1500,10),now());return json({ok:true})}
 if(action==='review-teacher'){if(!u.admin)throw new Problem(403,'관리자만 승인할 수 있어.');const uid=str(b.userId,100,1);if(!await one('SELECT user_id FROM teacher_requests WHERE user_id=?',uid))throw new Problem(404,'신청을 찾을 수 없어.');const approved=b.approved===true;await db().batch([db().prepare('UPDATE teacher_requests SET status=? WHERE user_id=?').bind(approved?'approved':'rejected',uid),db().prepare('UPDATE profiles SET role=? WHERE id=?').bind(approved?'teacher':'student',uid)]);return json({ok:true})}
 if(action==='group-create'){if(p.role!=='teacher'&&!u.admin)throw new Problem(403,'선생님 인증이 승인되면 그룹을 만들 수 있어.');const gid=id(),code=Array.from(crypto.getRandomValues(new Uint8Array(8)),n=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[n%31]).join('');await db().batch([db().prepare('INSERT INTO groups(id,owner,name,code,created) VALUES(?,?,?,?,?)').bind(gid,u.userId,str(b.name,80,1),code,now()),db().prepare('INSERT INTO members(group_id,user_id,joined) VALUES(?,?,?)').bind(gid,u.userId,now())]);return json({id:gid})}
 if(action==='group-join'){const code=str(b.code,16,4).toUpperCase().replace(/\s/g,'');const g=await one('SELECT id FROM groups WHERE code=?',code);if(!g)throw new Problem(404,'코드를 찾을 수 없어. 선생님이 준 코드를 확인해 줘.');await write('INSERT OR IGNORE INTO members(group_id,user_id,joined) VALUES(?,?,?)',g.id,u.userId,now());return json({id:g.id})}
 if(action==='group-leave'){const g=await member(str(b.groupId,100,1),u.userId);if(g.owner===u.userId)throw new Problem(400,'그룹을 만든 선생님은 나갈 수 없어요.');await write('DELETE FROM members WHERE group_id=? AND user_id=?',g.id,u.userId);return json({ok:true})}
 if(action==='topic-create'){await owner(str(b.groupId,100,1),u.userId);const selected=topicCatalog.find(t=>t.id===b.catalogId);if(!selected)throw new Problem(400,'제공된 목록에서 주제를 선택해 주세요.');const due=str(b.due,40,1);if(!Number.isFinite(Date.parse(due))||Date.parse(due)<Date.now())throw new Problem(400,'토론 날짜는 앞으로의 날짜로 골라 줘.');const tid=id();await write('INSERT INTO topics(id,group_id,title,context,due,created) VALUES(?,?,?,?,?,?)',tid,b.groupId,selected.title,selected.context,new Date(due).toISOString(),now());return json({id:tid})}
 if(action==='topic-help'){if(p.role!=='teacher'&&!u.admin)throw new Problem(403,'인증된 선생님만 이용할 수 있어.');const title=str(b.title,160,1),context=str(b.context,6000);const result=await ai(u,[{role:'user',content:`수업 준비를 도와줘. 주제: ${title}. 내가 확인한 자료: ${context}. 수업 진행자를 위해 학생에게 결론을 암시하지 않는 진행 원칙과 추가로 검증할 자료 항목만 5개 이내로 제안해줘. 사실을 새로 지어내지 마.`}],'교사용 수업 준비. 제공된 내용을 넘는 사실은 검증할 대상으로 표시한다.');return json({answer:result})}
 if(action==='session-create'){const tid=str(b.topicId,100,1);let title='조선의 시작, 그리고 왕자의 난';if(tid){const t=await one('SELECT * FROM topics WHERE id=?',tid);if(!t)throw new Problem(404,'주제를 찾을 수 없어.');await member(t.group_id,u.userId);title=t.title}const sid=id();await write('INSERT INTO sessions(id,owner,topic_id,title,created,updated) VALUES(?,?,?,?,?,?)',sid,u.userId,tid,title,now(),now());return json({id:sid})}
 if(action==='chat'){const s=await ownSession(str(b.sessionId,100,1),u.userId);const message=str(b.message,2500,1);const prior=await all('SELECT role,content FROM messages WHERE session_id=? ORDER BY created DESC,id DESC LIMIT 24',s.id);let context=topicContext;if(s.topic_id){const t=await one('SELECT * FROM topics WHERE id=?',s.topic_id);if(t){await member(t.group_id,u.userId);context=t.title+'\n'+t.context+(lessonForTitle(t.title).id==='joseon-princes'?'\n'+topicContext:'');}}const {answer,notes}=await coach(u,[...prior.reverse().map(m=>({role:m.role,content:m.content})),{role:'user',content:message}],context,s);const stamp=now();await db().batch([db().prepare('INSERT INTO messages(id,session_id,role,content,created) VALUES(?,?,?,?,?)').bind(id(),s.id,'user',message,stamp),db().prepare('INSERT INTO messages(id,session_id,role,content,created) VALUES(?,?,?,?,?)').bind(id(),s.id,'assistant',answer,new Date(Date.now()+1).toISOString()),db().prepare('UPDATE sessions SET question=?,opinion=?,evidence=?,next_question=?,complete=0,updated=? WHERE id=? AND owner=?').bind(notes.question,notes.opinion,notes.evidence,notes.next_question,now(),s.id,u.userId),db().prepare('INSERT OR IGNORE INTO attendance(user_id,day) VALUES(?,?)').bind(u.userId,day())]);return json({answer,notes})}
 if(action==='save'){const s=await ownSession(str(b.sessionId,100,1),u.userId);const t=await one('SELECT group_id FROM topics WHERE id=?',s.topic_id);if(t)await member(t.group_id,u.userId);if(b.complete&&(!s.question||!s.opinion||!s.evidence))throw new Problem(400,'대화에서 내 질문과 생각, 직접 확인한 근거를 남기고 준비를 마쳐 줘.');await write('UPDATE sessions SET complete=?,updated=? WHERE id=? AND owner=?',b.complete?1:0,now(),s.id,u.userId);return json({ok:true})}
 if(action==='allocate'){const g=await owner(str(b.groupId,100,1),u.userId),tid=str(b.topicId,100,1);if(!await one('SELECT id FROM topics WHERE id=? AND group_id=?',tid,g.id))throw new Problem(404,'이 그룹의 주제가 아니야.');const roster=await all('SELECT p.id,p.nickname FROM profiles p JOIN members m ON p.id=m.user_id WHERE m.group_id=? AND p.id<>?',g.id,u.userId);const ready=await all('SELECT * FROM sessions WHERE topic_id=? ORDER BY updated DESC,id DESC',tid);const last=new Map<string,any>();for(const s of ready)if(!last.has(s.owner))last.set(s.owner,s);const history=await all('SELECT assignments FROM allocations WHERE group_id=?',g.id);const count:Record<string,number>={};for(const h of history){for(const a of JSON.parse(h.assignments)){if(a.role!=='jury')count[a.id]=(count[a.id]??0)+1}}const candidates=roster.filter(r=>last.get(r.id)?.complete).map(r=>({...last.get(r.id),id:r.id}));const topic=await one('SELECT title FROM topics WHERE id=?',tid);const roles=await assignDebate(u,topic.title,candidates,count);const assignments=roster.map(r=>({...r,role:roles.find((a:any)=>a.id===r.id)?.role||'jury'}));await write('INSERT INTO allocations(id,group_id,topic_id,assignments,created) VALUES(?,?,?,?,?)',id(),g.id,tid,JSON.stringify(assignments),now());return json({assignments})}
 throw new Problem(400,'알 수 없는 요청이야.');
 }catch(e){return fail(e)}}
